ARG BASE_IMAGE=alpine:3.20
FROM ${BASE_IMAGE}

# if needed, install additional dependencies here
ENV TZ=Asia/Shanghai

RUN apk update \
    && apk add --no-cache libgcc tzdata \
    && echo "${TZ}" > /etc/timezone \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && rm /var/cache/apk/*
