# 通过构建参数传递镜像名，默认为 rust:1.70.0-alpine3.17
ARG BASE_IMAGE=rust:1.70.0-alpine3.17
FROM ${BASE_IMAGE}

# 定义构建参数
# mold: https://github.com/rui314/mold/releases
ARG MOLD_VERSION=2.33.0 
# sccache：https://github.com/mozilla/sccache/releases
ARG SCCACHE_VERSION=0.8.1

WORKDIR /app

RUN apk update \
  && apk add --no-cache musl-dev pkgconfig openssl-dev clang wget make git bzip2 ca-certificates python3 bash build-base coreutils gcompat libgcc libc-dev

# 使用构建参数
RUN mkdir download && cd download \
  && wget https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-x86_64-linux.tar.gz && tar xzvf mold-${MOLD_VERSION}-x86_64-linux.tar.gz && mv mold-${MOLD_VERSION}-x86_64-linux ../mold \
  && wget https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz && tar xzvf sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz && mv sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl/sccache ../ && chmod +x /app/sccache \ 
  && apk del -f wget \
  && rm -rf /var/lib/apt/lists/* && rm -rf ../download

ENV TZ "Asia/Shanghai"
ENV CARGO_HOME="/rust-cache/cargo"
ENV RUSTC_WRAPPER="/app/sccache"
ENV SCCACHE_DIR="/rust-cache/sccache"
ENV UDOLPHIN_CONFIG "/udolphin/config.yaml"
ENV PATH "/udolphin:${PATH}"
ENV RUSTFLAGS="-C target-feature=-crt-static"

CMD /bin/bash