name: wasm-pack
on:
  push:
    tags:
      - 'wasm-pack*'

jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Extract Tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/wasm-pack})"
      - name: Build Image
        run: |
          docker build -t wasm-pack -f Dockerfile_wasm_pack .
      - name: Tag Image
        run: docker tag wasm-pack dk.uino.cn/runner/wasm-pack:${{ steps.extract_tag.outputs.tag }}
      - name: Login to Registry
        run: docker login --username='${{ secrets.DOCKER_USERNAME }}' --password ${{ secrets.DOCKER_PASSWORD }} dk.uino.cn
      - name: Push Image
        run: docker push dk.uino.cn/runner/wasm-pack:${{ steps.extract_tag.outputs.tag }}
