name: Docker Image CI/CD
on:
  push:
    branches: [ main ]
jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t dk.uino.cn/deno/deno_puppeteer:16.2.0-2 -f Dockerfile_puppeteer .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} dk.uino.cn
      - name: Push Image
        run: |
          docker push dk.uino.cn/deno/deno_puppeteer:16.2.0-2

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script: |
            # 切换工作区
            cd simcaptcha
            # 下载 docker-compose.yml
            wget -O docker-compose.yml https://raw.githubusercontent.com/yiyungent/SimCaptcha/master/docker-compose.yml
            # 停止并删除旧 容器、网络、挂载点
            #docker-compose down                          # TODO: docker-compose: command not found. 不知道为什么找不到 docker-compose，但直接连接服务器执行就可以
            /usr/local/python3/bin/docker-compose down
            # 删除旧镜像
            docker rmi yiyungent/simcaptcha 
            docker rmi yiyungent/simcaptcha-client
            # 登录镜像服务器
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 
            # 创建并启动容器
            #docker-compose up -d --build
            /usr/local/python3/bin/docker-compose up -d --build