name: npm 18
on:
  push:
    tags:
      - 'npm18-*' # npm18-18.0.4-alpine

jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Extract Tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/npm18-})"
      - name: Build Image
        run: |
          docker build -t npm -f npm/Dockerfile_18_alpine .
      - name: Tag Image
        run: docker tag npm dk.uino.cn/runner/node:${{ steps.extract_tag.outputs.tag }}
      - name: Login to Registry
        run: docker login --username='${{ secrets.DOCKER_USERNAME }}' --password ${{ secrets.DOCKER_PASSWORD }} dk.uino.cn
      - name: Push Image
        run: docker push dk.uino.cn/runner/node:${{ steps.extract_tag.outputs.tag }}
