name: Docker Image CI/CD
on:
  push:
    branches: [ main ]
jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t dk.uino.cn/deno/deno_puppeteer:16.2.0-2 -f Dockerfile_puppeteer .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} dk.uino.cn
      - name: Push Image
        run: |
          docker push dk.uino.cn/deno/deno_puppeteer:16.2.0-2
