name: npm
on:
  push:
    tags:
      - 'npm_*' # npm_18-alpine3.17_18.0.4-alpine，以下划线连接，第1段是npm，第2段是基础镜像名，也就是下面的BASE_IMAGE，第3段是要打的镜像的tag

jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2

      - name: Extract Tag
        id: extract_tag
        run: echo "tag=$(echo ${GITHUB_REF#refs/tags/npm_})" >> $GITHUB_OUTPUT

      - name: Extract Base Image
        id: extract_base_image
        run: echo "base_image=$(echo ${{ steps.extract_tag.outputs.tag }} | cut -d_ -f2)" >> $GITHUB_OUTPUT

      - name: Extract Image Tag
        id: extract_image_tag
        run: echo "image_tag=$(echo ${{ steps.extract_tag.outputs.tag }} | cut -d_ -f3)" >> $GITHUB_OUTPUT

      - name: Build Image
        run: |
          docker build --build-arg BASE_IMAGE=node:${{ steps.extract_base_image.outputs.base_image }} -t npm:${{ steps.extract_image_tag.outputs.image_tag }} .

      - name: Tag Image
        run: docker tag npm:${{ steps.extract_image_tag.outputs.image_tag }} dk.uino.cn/runner/node:${{ steps.extract_image_tag.outputs.image_tag }}

      - name: Login to Registry
        run: docker login --username='${{ secrets.DOCKER_USERNAME }}' --password ${{ secrets.DOCKER_PASSWORD }} dk.uino.cn

      - name: Push Image
        run: docker push dk.uino.cn/runner/node:${{ steps.extract_image_tag.outputs.image_tag }}