FROM node:18-alpine3.17

# 打印Node.js版本
RUN echo "Node.js version:" && node -v

RUN apk update \
    && apk add --no-cache git bzip2  ca-certificates python3 py3-pip \
    && rm /var/cache/apk/*

RUN npm install -g pnpm

# 打印pnpm版本号
RUN echo "pnpm version: " && pnpm -v
