# see: https://hub.docker.com/_/node/tags?page_size=&ordering=&name=20-alpine
FROM node:20-alpine3.20

# 打印Node.js版本
RUN echo "Node.js version:" && node -v

RUN apk update \
    && apk add --no-cache git bzip2  ca-certificates python3 py3-pip \
    && rm /var/cache/apk/*

RUN npm install -g pnpm

